ok
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'github.com:nianweijie/Hello-world.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.